spring.application.name=MiniProject

## 1. 드라이버 설정
spring.datasource.driver-class-name=org.postgresql.Driver

## 2. 연결 URL (Supabase 대시보드에서 복사)
## 형식: jdbc:postgresql://db.[ID].supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?currentSchema=miniproject,public,extensions
spring.jpa.properties.hibernate.default_schema=miniproject
## 3. 계정 정보
spring.datasource.username=postgres.zdpnkzsypfxtcywyeddq
spring.datasource.password=kdt202503toilet

## 4. 하이버네이트 방언(Dialect) 설정
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#batchsize 설정
spring.jpa.properties.hibernate.default_batch_fetch_size=100

##oauth2 설정 파일
spring.config.import=file:C:/workspace/work_miniproject/minioauth2.properties

app.frontend.url = https://10.125.121.182:3000/main
##"http://localhost:8080/login"
##"https://webfront-ashen.vercel.app" 
##"http://10.125.121.182:3000"
##네이버 구글 api 설정 필요

# HikariCP 커넥션 풀 설정 
spring.datasource.hikari.maximum-pool-size=3
# 연결 시도 타임아웃 (30초)
spring.datasource.hikari.connection-timeout=30000
# 세션이 살아있을 수 있는 최대 시간
spring.datasource.hikari.max-lifetime=1800000

# 서버 종료 시 커넥션을 정상적으로 반납하도록 유도
server.shutdown=graceful

# SQL의 '?' 자리에 어떤 파라미터가 들어가는지 확인 
#logging.level.org.hibernate.orm.jdbc.bind=trace

#배포용 baseurl 설정
ngrok-redirect.baseurl = https://unlabeled-engrossingly-fallon.ngrok-free.dev
#ngrok ip주소 변경 등록

spring.security.oauth2.client.registration.google.redirect-uri=${ngrok-redirect.baseurl}/login/oauth2/code/google

# 3. 프록시(ngrok) 서버의 호스트 정보를 스프링이 신뢰하도록 설정 (필수)
server.forward-headers-strategy=framework